#!/bin/bash/
#Author : Jupiter
#Date: 2/23
#Description: sonarqube installation on Centos 7"

echo "sonarqube installation successful"

#Step 1: Java 11 installation
sudo yum update -y

sudo yum install java-11-openjdk-devel -y

sudo yum install java-11-openjdk -y
#Step 2: Download SonarQube latest versions on your server
cd /opt
sudo yum install wget -y
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip

#Step 3: Extract packages
sudo yum install unzip -y
sudo unzip /opt/sonarqube-9.3.0.51899.zip

#Step 4: Change ownership to the user and Switch to Linux binaries directory to start service

sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899

cd /opt/sonarqube-x.x/bin/linux-x86-64 

 ./sonar.sh start
Connect to SonaQube
Connect to the SonarQube server through the browser using port 9000.

http://<your-ip-address>:9000


#sudo firewall-cmd --permanent --add-port=9000/tcpcd

# sudo firewall-cmd --reload